blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/not-elm/desktop-homunculus/discussions
    about: For questions and general help, please use GitHub Discussions.
