#!/usr/bin/env bash
# run-quality-agent.sh — quality-agent를 claude -p로 로컬 실행 후 PR 생성
# crontab: 7 9 * * * bash /home/spow12/codes/2025_lower/DesktopMatePlus/scripts/run-quality-agent.sh

set -euo pipefail

WORKSPACE="/home/spow12/codes/2025_lower/DesktopMatePlus"
LOG_DIR="$WORKSPACE/docs/reports"
DATE=$(date +%Y-%m-%d)
BRANCH="quality/report-${DATE}"
LOG_FILE="$LOG_DIR/quality-${DATE}.md"

cd "$WORKSPACE"

# ── 1. feature 브랜치 생성 ────────────────────────────────────────
git fetch origin master
git checkout -b "$BRANCH" origin/master

# ── 2. quality-agent 실행 ─────────────────────────────────────────
claude -p "
You are the quality-agent for this workspace. Follow the checklist in .claude/agents/quality-agent.md exactly.

1. Run: bash scripts/garden.sh --metrics
2. Run: bash scripts/check_docs.sh
3. Check stale cc:TODO tasks in Plans.md (older than 14 days based on git log)
4. Check archive bloat: count completed Phases in Plans.md and completed items in docs/TODO.md
5. Write the full report to: docs/reports/quality-${DATE}.md

Use the report format defined in .claude/agents/quality-agent.md.
" \
  --allowedTools "Bash,Read,Write,Grep,Glob" \
  --output-format json \
  >> "$LOG_FILE.run.log" 2>&1

# ── 3. 변경사항 없으면 브랜치 삭제 후 종료 ───────────────────────
if ! git diff --quiet || git ls-files --others --exclude-standard | grep -q .; then
  git add docs/reports/ docs/QUALITY_SCORE.md 2>/dev/null || true
  git commit -m "chore: quality report ${DATE}

Auto-generated by quality-agent (scripts/run-quality-agent.sh).
"
  git push -u origin "$BRANCH"

  # ── 4. PR 생성 ──────────────────────────────────────────────────
  gh pr create \
    --base master \
    --title "chore: quality report ${DATE}" \
    --body "$(cat <<EOF
## Quality Report — ${DATE}

Auto-generated by \`quality-agent\` (daily cron, 09:07 KST).

Report: \`docs/reports/quality-${DATE}.md\`

> Review violations and recommendations, then merge or close.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
EOF
)"
  echo "[$(date)] PR created for quality report ${DATE}" >> "$LOG_DIR/cron.log"
else
  git checkout master
  git branch -d "$BRANCH"
  echo "[$(date)] No changes — skipped PR" >> "$LOG_DIR/cron.log"
fi
