#!/usr/bin/env bash
# run-quality-agent.sh — quality-agent를 claude -p로 로컬 실행 후 PR 생성
# crontab: 7 9 * * * bash /home/spow12/codes/2025_lower/DesktopMatePlus/scripts/run-quality-agent.sh

set -euo pipefail

CLAUDE_BIN="/home/spow12/.local/bin/claude"
WORKSPACE="/home/spow12/codes/2025_lower/DesktopMatePlus"
DATE=$(date +%Y-%m-%d)
YEAR=$(date +%Y)
MONTH=$(date +%m)
REPORT_DIR="$WORKSPACE/docs/reports/${YEAR}/${MONTH}"
LOG_DIR="$WORKSPACE/docs/reports"
BRANCH="quality/report-${DATE}"
REPORT_FILE="$REPORT_DIR/quality-${DATE}.md"

cd "$WORKSPACE"
mkdir -p "$REPORT_DIR"

# ── cleanup trap: 실패 시 브랜치 정리 ────────────────────────────────
cleanup() {
  local exit_code=$?
  if [ $exit_code -ne 0 ]; then
    echo "[$(date)] ERROR: run-quality-agent.sh failed (exit $exit_code)" >> "$LOG_DIR/cron.log"
    # 현재 브랜치가 quality 브랜치면 master로 복귀 후 삭제
    if git rev-parse --abbrev-ref HEAD | grep -q "^quality/"; then
      git checkout master 2>/dev/null || true
      git branch -D "$BRANCH" 2>/dev/null || true
    fi
  fi
}
trap cleanup EXIT

# ── 1. feature 브랜치 생성 ────────────────────────────────────────
git fetch origin master
# 이미 존재하는 경우 재사용 (-B: create or reset)
git checkout -B "$BRANCH" origin/master

# ── 2. quality-agent 실행 ─────────────────────────────────────────
"$CLAUDE_BIN" -p "
You are the quality-agent for this workspace. Follow the checklist in .claude/agents/quality-agent.md exactly.

1. Run GP drift detection (read-only): bash scripts/garden.sh --dry-run
2. Run dead link / oversized doc check: bash scripts/check_docs.sh --dry-run
3. Check stale cc:TODO tasks in Plans.md (older than 14 days based on git log)
4. Check archive bloat: count completed Phases in Plans.md and completed items in docs/TODO.md
5. Update quality score: bash scripts/garden.sh --metrics
6. Write the full report to: docs/reports/${YEAR}/${MONTH}/quality-${DATE}.md

Use the report format defined in .claude/agents/quality-agent.md.
" \
  --allowedTools "Bash,Read,Write,Grep,Glob" \
  >> "$REPORT_FILE.run.log" 2>&1

# ── 3. 변경사항 없으면 브랜치 삭제 후 종료 ───────────────────────
if ! git diff --quiet || git ls-files --others --exclude-standard | grep -q .; then
  git add docs/reports/ docs/QUALITY_SCORE.md 2>/dev/null || true
  git commit -m "chore: quality report ${DATE}

Auto-generated by quality-agent (scripts/run-quality-agent.sh).
"
  git push -u origin "$BRANCH"

  # ── 4. Recommendations 파싱 → 체크박스 생성 ─────────────────────
  CHECKLIST=""
  if [ -f "$REPORT_FILE" ]; then
    CHECKLIST=$(awk '/^## Recommendations/{found=1; next} found && /^---/{exit} found && /^[0-9]+\./{
      sub(/^[0-9]+\. /, "")
      gsub(/\*\*/, "")
      print "- [ ] " $0
    }' "$REPORT_FILE")
  fi

  CHECKLIST_SECTION=""
  if [ -n "$CHECKLIST" ]; then
    CHECKLIST_SECTION="## Checklist — 모든 항목 완료 후 머지

${CHECKLIST}

> 조치 불필요 항목은 직접 체크 후 머지. 미체크 항목이 남아있으면 pr-merge-agent가 머지를 블록합니다."
  fi

  # ── 5. PR 생성 ──────────────────────────────────────────────────
  # violation count 집계
  VIOLATION_COUNT=$(awk '/^## Violations Summary/{found=1; next} found && /^---/{exit} found && /violations/{print}' "$REPORT_FILE" 2>/dev/null | grep -v "0 violations" | wc -l | tr -d ' ')

  gh pr create \
    --base master \
    --title "chore: quality report ${DATE}" \
    --body "$(cat <<EOF
## Problem

Daily quality check found ${VIOLATION_COUNT} violation type(s) on ${DATE}. See full report: \`docs/reports/${YEAR}/${MONTH}/quality-${DATE}.md\`

## Solution

Auto-generated quality report by \`quality-agent\` (daily cron, 09:07 KST).
Review each item in the checklist below and either fix or mark as acknowledged.

---

- [ ] If HTTP endpoints changed: I ran \`make gen-open-api\` and \`pnpm build\`
- [ ] This PR includes breaking changes

${CHECKLIST_SECTION}

🤖 Generated with [Claude Code](https://claude.com/claude-code)
EOF
)"
  echo "[$(date)] PR created for quality report ${DATE}" >> "$LOG_DIR/cron.log"
else
  git checkout master
  git branch -d "$BRANCH"
  echo "[$(date)] No changes — skipped PR" >> "$LOG_DIR/cron.log"
fi
